server:
  port: 1001

eureka:
  client:
    register-with-eureka: false #是否将自己注册到 Eureka Server
    fetch-registry: false #是否从 Eureka Server 获取注册信息。目前做的是单点，不需要同步其他节点的信息
    service-url:
      defaultZone: http://localhost:1001/eureka/ # 与 Eureka Server 交互地址，多个可用,分割

